name: polka_clients
description: "A new Flutter project."
publish_to: 'none'
version: 3.3.3+225

environment:
  sdk: ^3.8.1
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared:
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  add_2_calendar: ^3.0.1
  map_launcher: ^4.4.2
  image_picker: ^1.2.0
  cached_network_image: ^3.4.1
  web_socket_channel: ^3.0.3
  collection: ^1.19.1
  yandex_maps_mapkit_lite: ^4.22.0-beta
  permission_handler: ^12.0.1
  flutter_svg: ^2.2.1
  infinite_scroll_pagination: ^5.1.1
  geolocator: ^14.0.2
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # Fonts from other packages need to be explicitly described
  fonts:
    - family: Manrope
      fonts:
        - asset: packages/shared/fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: packages/shared/fonts/Manrope-Light.ttf
          weight: 300
        - asset: packages/shared/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: packages/shared/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: packages/shared/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: packages/shared/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: packages/shared/fonts/Manrope-ExtraBold.ttf
          weight: 800
