name: polka_masters
description: "A new Flutter project."
publish_to: 'none'
version: 2.5.1+52

environment:
  sdk: ^3.8.1
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  shared:
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  provider: ^6.1.5+1
  image_picker: ^1.2.0
  flutter_secure_storage: ^9.2.4
  calendar_view:
    path: ../../packages/calendar_view
  equatable: ^2.0.7
  fast_contacts: ^5.0.1
  permission_handler: ^12.0.1
  appmetrica_plugin: ^3.3.0
  infinite_scroll_pagination: ^5.1.1
  webview_flutter: ^4.13.0
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
  # Fonts from other packages need to be explicitly described
  fonts:
    - family: Manrope
      fonts:
        - asset: packages/shared/fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: packages/shared/fonts/Manrope-Light.ttf
          weight: 300
        - asset: packages/shared/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: packages/shared/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: packages/shared/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: packages/shared/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: packages/shared/fonts/Manrope-ExtraBold.ttf
          weight: 800
    - family: Inter
      fonts:
        - asset: packages/shared/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: packages/shared/fonts/Inter-Light.ttf
          weight: 300
        - asset: packages/shared/fonts/Inter-Regular.ttf
          weight: 400
        - asset: packages/shared/fonts/Inter-Medium.ttf
          weight: 500
        - asset: packages/shared/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: packages/shared/fonts/Inter-Bold.ttf
          weight: 700
        - asset: packages/shared/fonts/Inter-ExtraBold.ttf
          weight: 800
